# Generated by Django 5.0.7 on 2024-08-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='main.OrderPosition', to='main.product'),
        ),
    ]
