# Generated by Django 5.0.7 on 2024-09-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='crated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
