# Generated by Django 5.0.7 on 2024-09-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_sensor_measurements_measurement_sensor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='sensor_id',
            new_name='sensor',
        ),
    ]
