# Generated by Django 5.1 on 2024-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_phones_image_phones_lte_exists_phones_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
