# Generated by Django 5.1 on 2024-08-27 22:05

from django.db import migrations

def copydata(apps,schema_editor):
    Student = apps.get_model('school', 'Student')
    for student in Student.objects.all():
        print(f'Added student id: {student.id}')
        x = Student.objects.get(id=student.id)
        print(f'Added teacher id: {student.teacher_id}')
        x.teachers.add(student.teacher_id)

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_teachers'),
    ]

    operations = [
        migrations.RunPython(copydata)
    ]
