GET http://localhost:8000/api

###

POST http://localhost:8000/api/


###
GET http://localhost:8000/api/weapon/1/

###
GET http://localhost:8000/api/weaponlist

###
POST http://localhost:8000/api/weaponlist/
Content-Type: application/json

{
  "power": 500,
  "rarity": "superpuper2",
  "value": 333
}